Commands:
  notFromConsole: "&cThis command cannot be run from the console!"
  permissionDenied: "&cYou don't have permission to use this!"
  manageStart: "&aRight click a container block with a {0} to toggle a honeychest. When finished, use /hc again."
  manageFinish: "&aHoneychest management mode finished."
  dataSaved: "&aHoneychest data saved to file!"
  dataSaveError: "&cAn error occured on saving honeychest data."
  dataLoaded: "&aHoneychest data loaded from file!"
  dataLoadError: "&cAn error occured on loading honeychest data."
BlockListener:
  notBreakTrap: "&cYou can't break Honeychest!"
  notPlaceChest: "&cThere is a Honeychest next to. Please remove it first."
PlayerListener:
  createTrap: "&aHoneychest created. Right click again to remove the Honeychest"
  removeTrap: "&aHoneychest removed!"
  openedTrap: "&csorry, this container has been opened by others."
Broadcast:
  alert: "&7Player&4 {0} &7was caught stealing from honeychest."
  items: "&6Stolen Item(s): &4{0}"